Add logs
RxThunder/RabbitMQ pull request #3
Opened 2019-09-10 06:51 UTC by TomPradat

2019-09-10 08:45 UTC, Th3Mouk commented on src/Router/Adapter.php
> +                'reason' => $e->getMessage(),
IMO `reason|file|line` it's not needed because we are capturing the whole exception.

Have you test the render in Sentry and stdout ?

2019-09-10 09:01 UTC, Th3Mouk requested changes

2019-09-10 09:01 UTC, Th3Mouk commented on src/Router/Adapter.php
> +                'reason' => $e->getMessage(),
Things are a little more complex than I expected on this case.
All informations are currently contained in the exception.

The aim here was to print some informations in stdout, then capture the exception with the logger.

But if we strictly replace `echo`s by a logger call with level debug or info, we call twice the logger for the same reason at different levels.

Here the solution can be the usage of [LineFormatter](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/LineFormatter.php) by the final user and simply delete `reason|file|line` keys.

2019-10-01 09:24 UTC, Th3Mouk requested changes

2019-10-01 09:24 UTC, Th3Mouk commented on src/Router/Adapter.php
> +                $this->logger->warning("ack but due to acceptable exception {$message->getRoutingKey()}");
This should be a notice IMO

2019-10-01 09:25 UTC, Th3Mouk commented
Can you please change the commit message by something more accurate like `replace echo by a logger` ty

2019-10-01 14:47 UTC, TomPradat commented
I'll refactor the message when squashing commit, if you're ok with the code

2019-10-01 14:50 UTC, Th3Mouk requested changes

2019-10-01 14:50 UTC, Th3Mouk commented on src/Router/Adapter.php
> +            $this->logger->error($e);
Can you please add the exception in the same call like this

```
$this->logger->notice('message', [
        'exception' => $previous
]);	                 
```

2019-10-01 14:50 UTC, Th3Mouk commented on src/Router/Adapter.php
> +                $this->logger->error($e);
Can you please add the exception in the same call like this

```
$this->logger->notice('message', [
        'exception' => $previous
]);	                 
```

2019-10-01 14:50 UTC, Th3Mouk commented on src/Router/Adapter.php
> +                $this->logger->warning($e);
Can you please add the exception in the same call like this

```
$this->logger->notice('message', [
        'exception' => $previous
]);	                 
```

2019-10-01 14:50 UTC, Th3Mouk commented on src/Router/Adapter.php
> +                    $this->logger->notice($previous, [
Can you delete this one please add attach the exception to the call above please ?

2019-10-01 14:53 UTC, Th3Mouk requested changes

2019-10-01 14:53 UTC, Th3Mouk commented on src/Router/Adapter.php
>                          'routing_key' => $dataModel->getType(),
can you remove this line please ?

2019-10-01 14:53 UTC, Th3Mouk commented on src/Router/Adapter.php
>                          'payload' => $message->getData(),
Add this one too

2019-10-01 15:07 UTC, Th3Mouk requested changes

2019-10-01 15:07 UTC, Th3Mouk commented on src/Router/Adapter.php
> -                if ($previous = $e->getPrevious()) {
This one is important `getPrevious()` can be null you can make an if/else

2019-10-01 15:15 UTC, Th3Mouk approved these changes

2019-10-01 15:38 UTC, merged